### ISSUE TITLE
Permissions for invoice info

### ISSUE THREAD

**Issue by sharafian** [interledger/open-payments#10]
When we talked about the invoice API in slack it sounded pretty definitive that you wanted the invoice balance to be privileged information that required the subject to auth with a site in order for a site to access it. But in this doc all the examples show the invoice balance coming back with the normal SPSP query information, with no extra auth. I'm curious what the rationale is there

**Comment by adrianhopebailie** [comment]
Our thinking is as follows, I'll add this to the doc later:

Firstly, permissions on the invoice is controlled by the issuer (wallet) and subject (account holder). The subject decides which third parties have permission to add/edit/view invoices and the wallet decides which functions to implement.

Second, I think we'd want to also differentiate between viewing the basic invoice (id, and STREAM credentials) and viewing the "full" invoice (id, STREAM credentials, balance etc) and have different permissions for each.

There are 3 ways to give the website access to the balance:

1. The subject chooses to make this available without authentication (as currently documented)
2. The subject gives permission to the website to view balances on invoices
3. The subject gives permission to the website to create invoices and view the balances on their own invoices

Option 1 is obviously not great as anyone that knows an invoice URL can get the full details.

Option 2 is better but the website still has the ability to see invoices that it didn't create. One way to get around this is that the subject could create a special Payment Pointer just for the website and use this for WM. When the invoices are created they will be for that PP and the user could give the website permissions to view all invoices for that PP.

Option 3 would require some changes to how websites do WM as they'd no longer be allowing the browser to create the invoice they'd be telling the browser which invoice to use. That said, if the invoice URL was used in the meta tag then the browser could just GET that (instead of the user's PP URL) and it would get a valid response. The only difference being that the invoice id would already be defined and the headers passed by the browser would be ignored.
