### ISSUE TITLE
Move AS<>IdP spec out of this repo

### ISSUE THREAD

**Issue by sabineschaller** [interledger/open-payments#198]
and potentially also the AS<>RS spec.

I still think the AS<>RS spec should stay because it is modeled after the GNAP Resource server spec. 
@adrianhopebailie @wilsonianb

**Comment by adrianhopebailie** [comment]
But is that a reason to make it part of the Open Payments standard?

If you look at the introduction of the GNAP RS spec it says:
> The core GNAP protocol does not define any one specific mechanism for the resource server (RS) to communicate with the authorization server (AS), allowing the connection between these components to be solved orthogonally to the core protocol's concerns

The same applies for Open Payments. If we make this RS <> AS spec part of the standard we impose a lot of implementation burden on implementors that might want to build some much simpler because they know they will only ever have a single server that runs both the AS and RS components.

Let's wait and see if there is a need for interop between RS and AS implementations before we add anything more to the standard. If that time comes, we have a well defined spec in Rafiki that can be adopted as the standard.

**Comment by sabineschaller** [comment]
I still think of the Rafiki AS as a reference implementation that can be plugged in and out. For AS' to be plug-able, the RS <> AS interaction should be standardized. But I see that this may be a weak argument and I guess I can be convinced to not standardize it for now.

**Comment by adrianhopebailie** [comment]
Resolved in #205
