### ISSUE TITLE
Replace `ilpStreamConnection` with methods/transports

### ISSUE THREAD

**Issue by wilsonianb** [interledger/open-payments#219]
Including `ilpStreamConnection` in the Open Payments spec makes Open Payments dependent on [STREAM](https://interledger.org/rfcs/0029-stream/) and ILP, generally.

An incoming payment `GET` response should instead include a `methods` or `transports` list that could STREAM connection details and/or [PSKv2](https://interledger.org/rfcs/0025-pre-shared-key-2/) info and/or TBD, none of which should be defined in the Open Payments standard.

This seems to also beg the question: Does this repo belong in the `interledger` org?

- This would make https://github.com/interledger/open-payments/issues/196 obsolete.

**Comment by sabineschaller** [comment]
I'm afraid this could break interoperability. If we decouple Open Payments from ILP, you never know if your counterparty's incoming payment allows for a method that you can support. According to @sappenin, this was one reason for PayString to fail. 
Even with supporting different Transport layer protocols, we could run into interoperability issues.

**Comment by adrianhopebailie** [comment]
I think this does warrant some deeper discussion.

> According to @sappenin, this was one reason for PayString to fail.

This was my understanding too, but I wonder if the fragmentation of the systems they were trying to connect was a contributing factor. I.e. Lots of different cryptos and fiat systems

Can we narrow the "methods" down to a small set that we feel confident about initially and then grow from there?

**Comment by adrianhopebailie** [comment]
> Does this repo belong in the interledger org?

I think so.

For me Interledger is not just about the protocols we have already defined but about a mission of creating inclusion through interoperability and finding whatever technical solutions we can to create an open and universal payment network.

If there are layers in the current ILP stack that aren't working we shouldn't try to force them into our solutions (e.g. STREAM for P2P payments). We should be solving problems by coming up with solutions, not finding problems we can apply our existing solutions to.

Open Payments solves a very specific problem around "setting up" a payment between the payer and payee (possibly facilitated by third-party). If we assume all parties are connected via STREAM then that is a useful assumption but if we find it's not a valid one then we should adapt.

To me, that doesn't make Open Payments something outside of Interledger, it just means Interledger is evolving.

**Comment by wilsonianb** [comment]
I think you've captured the ILP Summit hack room discussion about: Interledger the protocol vs Interledger the idea(?)

I like Interledger the mission, but switching to ILM makes it seems like our mission is to just test Disney copyright/trademark.

**Comment by sappenin** [comment]
> I'm afraid this could break interoperability. If we decouple Open Payments from ILP, you never know if your counterparty's incoming payment allows for a method that you can support. According to @sappenin, this was one reason for PayString to fail.

Just wanted to clarify my comments from the summit. I don't think we should decouple OP from ILP -- just that I've been thinking about alternatives to STREAM that would still be ILP-compatible (and negotiated at the ILP layer). It's possible that this new alternative-to-STREAM idea I've been mulling over might still use something like a STREAM connection anyway for compatibility purposes.

> This seems to also beg the question: Does this repo belong in the interledger org?

I think yes, FWIW -- I agree with the post by @adrianhopebailie.

> Can we narrow the "methods" down to a small set that we feel confident about initially and then grow from there?

I would be fine just using STREAM for now -- It's probably not worth muddying the OP spec until and unless some STREAM alternative comes about (assuming it's even possible - it may not be possible, in which case STREAM is all we have).

All that to say -- we can probably close this issue (although that assumes @wilsonianb created this in response to our conversation with @sabineschaller after her talk. However, I wasn't involved in the "ILP Summit hack room discussion", so perhaps there's some context I'm missing and maybe this issue is related more to something discussed there).
