### ISSUE TITLE
Introduce Payment Received ACK?

### ISSUE THREAD

**Issue by sappenin** [interledger/open-payments#42]
One feedback from financial institutions around payments more broadly is around "payment certainty" -- meaning in a closed loop environment (e.g., Venmo to Venmo), it's fairly easy / riskless to ensure the right receiver receives the right funds.  But it's more difficult to determine if a receiver was paid correctly when two decentralized services are interacting.

One way we can help introduce the concept of "payment certainty" is for the receiver to send a payment ack back to the sender using the Oauth access token for a mandate. This could be an indicator from the receiver wallet to the sender wallet around "payment certainty."

**Comment by sharafian** [comment]
Making the communication from wallet to client bidirectional could make the security more complicated

**Comment by sappenin** [comment]
True - though I'm unclear what you mean by "wallet" and "client". In a subscription flow, there's some system (like a merchant processing sytem, e.g.) that makes a call to a mandate's `/charges` endpoint. To make this call, a bearer token is required, and that token could be used to "ACK" a payment.

**Comment by kincaidoneil** [comment]
> financial institutions around payments more broadly is around "payment certainty" -- meaning in a closed loop environment (e.g., Venmo to Venmo), it's fairly easy / riskless to ensure the right receiver receives the right funds. But it's more difficult to determine if a receiver was paid correctly when two decentralized services are interacting.

Why does a fulfillment not provide this payment certainty for a single ILP packet? And why does the aggregation of many fulfillments not suffice for an Open Payments payment?

**Comment by sappenin** [comment]
I'm going to quote @nhartner here because this is something he's identifying while trying to POC the mandates/subscriptions flows, and it's probably worth circulating this more broadly for more feedback.

> The issue isn’t the payment layer ack’ing...the issue is having the Open Payment operator ack that it got the payment for a specific transaction. The payment layer could succeed but the Open Payment layer could miss the payment if it wasn’t tagged properly, or the receiver has a system issue or if it wasn’t sent to the right address.

**Comment by kincaidoneil** [comment]
> The issue isn’t the payment layer ack’ing...the issue is having the Open Payment operator ack that it got the payment for a specific transaction. The payment layer could succeed but the Open Payment layer could miss the payment if it wasn’t tagged properly, or the receiver has a system issue or if it wasn’t sent to the right address.

Yeah, I agree that a failure/bugs reconciling the a fulfilled STREAM packet with the Open Payments layer could cause inconsistences. A couple thoughts on this:

1. If the STREAM sender does not fulfill the packet until after it has received an ACK from the Open Payments layer that the amount was successfully credited to the user's account, none of these scenarios should be an issue (improper tagging, receiver system issue, correct address). This puts slightly more risk on the operator, but this is still the typical fulfillment risk/bisected packet scenario, which will exist either way. Separately, I have some ideas on mitigations for this.

2. Instead, suppose we don't implement it like that, but instead STREAM immediately fulfills the packet, and emits some non-blocking event to the Open Payments layer -- and for some reason, this fails to be correctly credited, but the packet was already fulfilled.

The sender (correctly) believes they have delivered the whole amount, but the recipient does not. I imagine this would manifest itself with merchant displaying some UI that it hasn't received any payment. Isn't this inevitable whether we have out-of-band ACKs or not? The sender's wallet reports, "merchant was fully paid," in which case, the sender must go to the merchant to resolve the issue. The beauty of STREAM is the sender wallet _knows_ with certainty that it's the receiver who is misbehaving (intentionally or not), so they go to the merchant for reconciliation -- which is what should happen, since the merchant _did_ get the money.

Now, back to the proposal: I'm not sure how some out of band payment ACKs improve this scenario. What is the Open Payments/STREAM sender supposed to do? After it gets a Fulfill, wait for an out-of-band ACK, then wait before sending another packet? Only send _x_ amount without receiving an ACK? What if the incoming payments were correctly credited, but the ACKs are simply delayed? Then, should the payment fail? In the failure case, it seems that results in the same scenario as above -- the sender must go to the merchant for reconciliation.
